"""Add Jobs table

Revision ID: 29d07b6163e7
Revises: c2b0d34aceb5
Create Date: 2026-07-11 17:14:02.975187

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29d07b6163e7"
down_revision: str | Sequence[str] | None = "c2b0d34aceb5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dedup_hash", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("company_name", sa.String(), nullable=False),
        sa.Column("domain_name", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("job_function", sa.String(), nullable=True),
        sa.Column(
            "seniority",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("employment_type", sa.String(), nullable=True),
        sa.Column("remote_type", sa.String(), nullable=True),
        sa.Column(
            "locations",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "countries",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "required_skills",
            postgresql.ARRAY(sa.String()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("employee_count", sa.String(), nullable=True),
        sa.Column("funding", sa.String(), nullable=True),
        sa.Column("company_summary", sa.String(), nullable=True),
        sa.Column("status", sa.String(), server_default="active", nullable=False),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("fallback_source", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_jobs_countries_gin",
        "jobs",
        ["countries"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_jobs_locations_gin",
        "jobs",
        ["locations"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_jobs_required_skills_gin",
        "jobs",
        ["required_skills"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_jobs_seniority_gin",
        "jobs",
        ["seniority"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(op.f("ix_jobs_dedup_hash"), "jobs", ["dedup_hash"], unique=True)
    op.create_table(
        "job_descriptions",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("cleaned_text", sa.Text(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_table(
        "job_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("source_name", sa.String(), nullable=False),
        sa.Column("source_job_id", sa.String(), nullable=False),
        sa.Column("source_url", sa.String(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "last_checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "unconfirmed_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_name", "source_job_id", name="uq_job_sources_name_job_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_sources")
    op.drop_table("job_descriptions")
    op.drop_index(op.f("ix_jobs_dedup_hash"), table_name="jobs")
    op.drop_index("idx_jobs_seniority_gin", table_name="jobs", postgresql_using="gin")
    op.drop_index(
        "idx_jobs_required_skills_gin", table_name="jobs", postgresql_using="gin"
    )
    op.drop_index("idx_jobs_locations_gin", table_name="jobs", postgresql_using="gin")
    op.drop_index("idx_jobs_countries_gin", table_name="jobs", postgresql_using="gin")
    op.drop_table("jobs")
    # ### end Alembic commands ###
