"""Add embeddings table

Revision ID: 2f8908e87bfd
Revises: 187a229592cd
Create Date: 2026-07-11 17:22:39.948688

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f8908e87bfd"
down_revision: str | Sequence[str] | None = "187a229592cd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "entity_type",
            sa.Enum("job", "career_memory", name="entitytype"),
            nullable=False,
        ),
        sa.Column("entity_id", sa.UUID(), nullable=False),
        sa.Column("embedding_input_hash", sa.String(), nullable=False),
        sa.Column(
            "vector", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=False
        ),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "valid_until",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW() + INTERVAL '7 days'"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_embeddings_embedding_input_hash"),
        "embeddings",
        ["embedding_input_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_embeddings_entity_id"), "embeddings", ["entity_id"], unique=False
    )
    op.create_index(
        "ix_embeddings_vector_hnsw",
        "embeddings",
        ["vector"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"vector": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_embeddings_vector_hnsw",
        table_name="embeddings",
        postgresql_using="hnsw",
        postgresql_ops={"vector": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_embeddings_entity_id"), table_name="embeddings")
    op.drop_index(op.f("ix_embeddings_embedding_input_hash"), table_name="embeddings")
    op.drop_table("embeddings")
    # ### end Alembic commands ###
