"""Add Jobs table

Revision ID: c2b0d34aceb5
Revises: cdee447e7756
Create Date: 2026-07-11 17:09:54.383899

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c2b0d34aceb5"
down_revision: str | Sequence[str] | None = "cdee447e7756"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
